name: student_attendance
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_ui_auth: ^3.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  firebase_ui_oauth_google: ^2.0.0
  cloud_firestore: ^6.0.1
  # firebase_auth: ^6.0.2
  qr_flutter: ^4.1.0
  # qr_code_scanner: ^1.0.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  mobile_scanner: ^7.0.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  month_picker_dialog: ^6.5.0
  pdf: ^3.11.3
  csv: ^6.0.0
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/
    - assets/logo.png
  uses-material-design: true
  fonts:
    - family: Handwriting
      fonts:
        - asset: assets/fonts/handwriting.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"   # <-- your logo file
  adaptive_icon_background: "#ffffff"   # Android adaptive icon background
  adaptive_icon_foreground: "assets/logo.png"
