// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuKakj3WphMiSGjCxKUkyw9AwbAtBaooQ',
    appId: '1:1024089483193:web:616d181ebf129c5802f868',
    messagingSenderId: '1024089483193',
    projectId: 'student-attendance-bhss',
    authDomain: 'student-attendance-bhss.firebaseapp.com',
    storageBucket: 'student-attendance-bhss.firebasestorage.app',
    measurementId: 'G-K0H5C33KNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Vi6aY4eV2OtD14x9uxTb0LZhPcEjbG0',
    appId: '1:1024089483193:android:63a3b17ff95a399802f868',
    messagingSenderId: '1024089483193',
    projectId: 'student-attendance-bhss',
    storageBucket: 'student-attendance-bhss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwhoDwtRXDxtmTKylUM1DRtUhOq4EYxIU',
    appId: '1:1024089483193:ios:5734aba94716a45002f868',
    messagingSenderId: '1024089483193',
    projectId: 'student-attendance-bhss',
    storageBucket: 'student-attendance-bhss.firebasestorage.app',
    androidClientId: '1024089483193-bhqciubakcaaqdm0hn1ndmhk801qdius.apps.googleusercontent.com',
    iosClientId: '1024089483193-h01k5oge6jfmma2vndg2nsavb99eo6ov.apps.googleusercontent.com',
    iosBundleId: 'com.developerruhban.studentattendanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwhoDwtRXDxtmTKylUM1DRtUhOq4EYxIU',
    appId: '1:1024089483193:ios:3fca725f3604437902f868',
    messagingSenderId: '1024089483193',
    projectId: 'student-attendance-bhss',
    storageBucket: 'student-attendance-bhss.firebasestorage.app',
    androidClientId: '1024089483193-bhqciubakcaaqdm0hn1ndmhk801qdius.apps.googleusercontent.com',
    iosClientId: '1024089483193-gnvr5v5bk3r1v3ooj7pbbs63e5p2i9qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuKakj3WphMiSGjCxKUkyw9AwbAtBaooQ',
    appId: '1:1024089483193:web:5be6264e522c899e02f868',
    messagingSenderId: '1024089483193',
    projectId: 'student-attendance-bhss',
    authDomain: 'student-attendance-bhss.firebaseapp.com',
    storageBucket: 'student-attendance-bhss.firebasestorage.app',
    measurementId: 'G-R0HLVKDXYX',
  );
}
